apiVersion: v1
kind: Service
metadata:
  name: lx-annotate
  namespace: lx-annotate
spec:
  type: ClusterIP
  selector:
    app: lx-annotate
  ports:
    - name: http
      port: 80
      targetPort: 8118
